### ISSUE TITLE
Doesn't work after upgrading to 4.1.0: Unknown custom element: <VueContext>

### ISSUE THREAD

**Issue by 2-5** [rawilk/vue-context#40]
After upgrading from 4.0.3 to 4.1.0, VueContext doesn't work anymore. 

The console shows the following error when loading the app:

`vue.runtime.esm.js:619 [Vue warn]: Unknown custom element: <VueContext> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

And the menu doesn't show up, instead I get this error:

`Uncaught TypeError: open is not a function`

**Comment by xrnv2** [comment]
Thanks for information, got same error with newest version (4.1.0) and after downgrade to 4.0.3 everything works fine.

**Comment by songsng** [comment]
me too

**Comment by mbasnap** [comment]
same problem

**Comment by renattonl** [comment]
same problem

**Comment by steven-jeanneret** [comment]
Same here.

**Comment by rawilk** [comment]
I am aware of the issue and will be resolving it hopefully soon. I figured out it's because I added sass to my build, which for some reason is breaking the component.

Sorry for any issues this has caused.

**Comment by rawilk** [comment]
Should be taken care of now.
